import pandas as pd

def get_tree_data():
    """
    Returns a dataset of tree species with their characteristics and suitability factors.
    In a production environment, this would be fetched from a database.
    """
    trees = [
        {
            "id": 1,
            "name": "Neem",
            "scientific_name": "Azadirachta indica",
            "growth_rate": "Medium",
            "mature_height": "15-20 m",
            "lifespan": "150-200 years",
            "native_region": "Indian Subcontinent",
            "climate_suitability": ["Tropical", "Subtropical"],
            "soil_suitability": ["Loamy", "Sandy", "Clay"],
            "drought_tolerance": "High",
            "water_needs": "Low",
            "environmental_benefits": "Excellent air purifier, natural pest repellent, medicinal properties",
            "purposes": ["Air Purification", "Shade", "Medicinal", "Carbon Sequestration"],
            "maintenance_level": "Low"
        },
        {
            "id": 2,
            "name": "Banyan",
            "scientific_name": "Ficus benghalensis",
            "growth_rate": "Medium",
            "mature_height": "20-30 m",
            "lifespan": "200-300 years",
            "native_region": "Indian Subcontinent",
            "climate_suitability": ["Tropical", "Subtropical"],
            "soil_suitability": ["Loamy", "Clay"],
            "drought_tolerance": "Medium",
            "water_needs": "Medium",
            "environmental_benefits": "Significant carbon sequestration, habitat for wildlife, soil conservation",
            "purposes": ["Shade", "Biodiversity", "Carbon Sequestration"],
            "maintenance_level": "Medium"
        },
        {
            "id": 3,
            "name": "Arjuna",
            "scientific_name": "Terminalia arjuna",
            "growth_rate": "Medium",
            "mature_height": "20-25 m",
            "lifespan": "100-150 years",
            "native_region": "Indian Subcontinent",
            "climate_suitability": ["Tropical", "Subtropical"],
            "soil_suitability": ["Loamy", "Sandy", "Riverbed"],
            "drought_tolerance": "Medium",
            "water_needs": "Medium",
            "environmental_benefits": "Strong carbon sequestration, supports riparian ecosystems, medicinal bark",
            "purposes": ["Medicinal", "Biodiversity", "Carbon Sequestration", "Erosion Control"],
            "maintenance_level": "Low"
        },
        {
            "id": 4,
            "name": "Peepal",
            "scientific_name": "Ficus religiosa",
            "growth_rate": "Fast",
            "mature_height": "20-30 m",
            "lifespan": "100-150 years",
            "native_region": "Indian Subcontinent",
            "climate_suitability": ["Tropical", "Subtropical"],
            "soil_suitability": ["Loamy", "Sandy", "Clay"],
            "drought_tolerance": "High",
            "water_needs": "Low",
            "environmental_benefits": "Exceptional oxygen production, significant carbon sequestration, habitat for wildlife",
            "purposes": ["Air Purification", "Shade", "Biodiversity", "Carbon Sequestration"],
            "maintenance_level": "Low"
        },
        {
            "id": 5,
            "name": "Gulmohar",
            "scientific_name": "Delonix regia",
            "growth_rate": "Fast",
            "mature_height": "10-15 m",
            "lifespan": "40-50 years",
            "native_region": "Madagascar",
            "climate_suitability": ["Tropical", "Subtropical"],
            "soil_suitability": ["Loamy", "Sandy"],
            "drought_tolerance": "High",
            "water_needs": "Low",
            "environmental_benefits": "Provides shade, reduces heat island effect, ornamental value",
            "purposes": ["Shade", "Ornamental", "Air Purification"],
            "maintenance_level": "Medium"
        },
        {
            "id": 6,
            "name": "Ashoka",
            "scientific_name": "Saraca asoca",
            "growth_rate": "Slow",
            "mature_height": "6-9 m",
            "lifespan": "60-80 years",
            "native_region": "Indian Subcontinent",
            "climate_suitability": ["Tropical", "Subtropical"],
            "soil_suitability": ["Loamy", "Clay"],
            "drought_tolerance": "Low",
            "water_needs": "High",
            "environmental_benefits": "Air purification, medicinal properties, ornamental value",
            "purposes": ["Medicinal", "Ornamental", "Air Purification"],
            "maintenance_level": "Medium"
        },
        {
            "id": 7,
            "name": "Mango",
            "scientific_name": "Mangifera indica",
            "growth_rate": "Medium",
            "mature_height": "10-15 m",
            "lifespan": "100-200 years",
            "native_region": "Indian Subcontinent",
            "climate_suitability": ["Tropical", "Subtropical"],
            "soil_suitability": ["Loamy", "Sandy", "Clay"],
            "drought_tolerance": "Medium",
            "water_needs": "Medium",
            "environmental_benefits": "Fruit production, carbon sequestration, habitat for birds",
            "purposes": ["Fruit Production", "Shade", "Biodiversity"],
            "maintenance_level": "High"
        },
        {
            "id": 8,
            "name": "Amaltas",
            "scientific_name": "Cassia fistula",
            "growth_rate": "Medium",
            "mature_height": "8-15 m",
            "lifespan": "50-100 years",
            "native_region": "Indian Subcontinent",
            "climate_suitability": ["Tropical", "Subtropical"],
            "soil_suitability": ["Loamy", "Sandy"],
            "drought_tolerance": "High",
            "water_needs": "Low",
            "environmental_benefits": "Nitrogen fixation, medicinal properties, ornamental value",
            "purposes": ["Medicinal", "Ornamental", "Soil Improvement"],
            "maintenance_level": "Low"
        },
        {
            "id": 9,
            "name": "Jamun",
            "scientific_name": "Syzygium cumini",
            "growth_rate": "Medium",
            "mature_height": "10-15 m",
            "lifespan": "80-100 years",
            "native_region": "Indian Subcontinent",
            "climate_suitability": ["Tropical", "Subtropical"],
            "soil_suitability": ["Loamy", "Sandy", "Clay"],
            "drought_tolerance": "Medium",
            "water_needs": "Medium",
            "environmental_benefits": "Fruit production, carbon sequestration, erosion control",
            "purposes": ["Fruit Production", "Shade", "Carbon Sequestration"],
            "maintenance_level": "Medium"
        },
        {
            "id": 10,
            "name": "Amla",
            "scientific_name": "Phyllanthus emblica",
            "growth_rate": "Medium",
            "mature_height": "8-18 m",
            "lifespan": "60-70 years",
            "native_region": "Indian Subcontinent",
            "climate_suitability": ["Tropical", "Subtropical", "Temperate"],
            "soil_suitability": ["Loamy", "Sandy", "Rocky"],
            "drought_tolerance": "High",
            "water_needs": "Low",
            "environmental_benefits": "Medicinal fruit, soil improvement, hardy in poor conditions",
            "purposes": ["Fruit Production", "Medicinal", "Soil Improvement"],
            "maintenance_level": "Low"
        },
        {
            "id": 11,
            "name": "Silver Oak",
            "scientific_name": "Grevillea robusta",
            "growth_rate": "Fast",
            "mature_height": "18-35 m",
            "lifespan": "60-80 years",
            "native_region": "Australia",
            "climate_suitability": ["Tropical", "Subtropical", "Temperate"],
            "soil_suitability": ["Loamy", "Sandy"],
            "drought_tolerance": "High",
            "water_needs": "Low",
            "environmental_benefits": "Windbreak, erosion control, timber production",
            "purposes": ["Windbreak", "Shade", "Timber"],
            "maintenance_level": "Low"
        },
        {
            "id": 12,
            "name": "Eucalyptus",
            "scientific_name": "Eucalyptus globulus",
            "growth_rate": "Fast",
            "mature_height": "30-55 m",
            "lifespan": "50-100 years",
            "native_region": "Australia",
            "climate_suitability": ["Tropical", "Subtropical", "Temperate"],
            "soil_suitability": ["Loamy", "Sandy", "Clay"],
            "drought_tolerance": "High",
            "water_needs": "Low",
            "environmental_benefits": "Fast carbon sequestration, timber, medicinal oil",
            "purposes": ["Carbon Sequestration", "Timber", "Medicinal"],
            "maintenance_level": "Low"
        },{
    'name': 'Guava (Amrood)',
    'scientific_name': 'Psidium guajava',
    'growth_rate': 'Fast',
    'mature_height': '10-15 feet',
    'lifespan': '15-20 years',
    'native_region': 'Tropical Americas, widely grown in India',
            "climate_suitability": ["Tropical", "Subtropical", "Temperate"],
            "soil_suitability": ["Loamy", "Sandy", "Clay"],
    'purposes': ['Fruit Production', 'Shade'],
    'environmental_benefits': 'Produces edible fruit, attracts pollinators, provides shade',
    'climate_zones': ['Tropical', 'Sub-tropical'],
    'soil_types': ['Loamy', 'Sandy', 'Clay'],
    'water_requirement': 'Medium',
    'co2_absorption_kg_year': 25
},
{
    'name': 'Papaya (Papita)',
    'scientific_name': 'Carica papaya',
    'growth_rate': 'Very Fast',
    'mature_height': '8-12 feet',
    'lifespan': '3-5 years',
    'native_region': 'Central America, cultivated in India',
    "climate_suitability": ["Tropical", "Subtropical", "Temperate"],
    "soil_suitability": ["Loamy", "Sandy"],
    'purposes': ['Fruit Production', 'Fast Growing'],
    'environmental_benefits': 'Quick fruit production, low water requirement',
    'climate_zones': ['Tropical', 'Sub-tropical'],
    'soil_types': ['Loamy', 'Sandy'],
    'water_requirement': 'Medium',
    'co2_absorption_kg_year': 20
},
{
    'name': 'Pomegranate (Anar)',
    'scientific_name': 'Punica granatum',
    'growth_rate': 'Medium',
    'mature_height': '12-15 feet',
    'lifespan': '15-20 years',
    'native_region': 'Iran, widely cultivated in India',
    "climate_suitability": ["Tropical", "Subtropical"],
    "soil_suitability": ["Loamy", "Sandy"],
    'purposes': ['Fruit Production', 'Medicinal'],
    'environmental_benefits': 'Drought-resistant, medicinal fruit, attracts birds',
    'climate_zones': ['Tropical', 'Sub-tropical', 'Temperate'],
    'soil_types': ['Loamy', 'Sandy'],
    'water_requirement': 'Low',
    'co2_absorption_kg_year': 22
},
{
    'name': 'Drumstick (Moringa)',
    'scientific_name': 'Moringa oleifera',
    'growth_rate': 'Very Fast',
    'mature_height': '25-30 feet',
    'lifespan': '15-20 years',
    'native_region': 'North India',
    "climate_suitability": ["Tropical", "Subtropical"],
    "soil_suitability": ["Loamy", "Sandy"],
    'purposes': ['Edible', 'Medicinal', 'Fast Growing'],
    'environmental_benefits': 'Superfood tree, drought-resistant, nitrogen-fixing',
    'climate_zones': ['Tropical', 'Sub-tropical'],
    'soil_types': ['Sandy', 'Loamy', 'Clay'],
    'water_requirement': 'Low',
    'co2_absorption_kg_year': 35
},
{
    'name': 'Curry Tree (Kadi Patta)',
    'scientific_name': 'Murraya koenigii',
    'growth_rate': 'Medium',
    'mature_height': '15-20 feet',
    'lifespan': '20-25 years',
    'native_region': 'India, Sri Lanka',
    "climate_suitability": ["Tropical", "Subtropical"],
    "soil_suitability": ["Loamy", "Sandy"],
    'purposes': ['Edible', 'Aromatic', 'Medicinal'],
    'environmental_benefits': 'Aromatic leaves, medicinal properties, attracts beneficial insects',
    'climate_zones': ['Tropical', 'Sub-tropical'],
    'soil_types': ['Loamy', 'Sandy'],
    'water_requirement': 'Medium',
    'co2_absorption_kg_year': 18
},
        {
            'name': 'Jackfruit (Kathal)',
            'scientific_name': 'Artocarpus heterophyllus',
            'growth_rate': 'Medium',
            'mature_height': '15-20 feet',
            'lifespan': '60-70 years',
            'native_region': 'Western Ghats, South India',
            "climate_suitability": ["Tropical", "Subtropical"],
            "soil_suitability": ["Loamy", "Sandy", "Clay"],
            'purposes': ['Fruit Production', 'Shade', 'Timber'],
            'environmental_benefits': 'Large fruits, dense canopy provides shade, timber use',
            'climate_zones': ['Tropical', 'Sub-tropical'],
            'soil_types': ['Loamy', 'Sandy', 'Clay'],
            'water_requirement': 'Medium',
            'drought_tolerance': 'Medium',
            'water_needs': 'Medium',
            'maintenance_level': 'Medium',
            'co2_absorption_kg_year': 28
        },
        {
            'name': 'Coconut (Nariyal)',
            'scientific_name': 'Cocos nucifera',
            'growth_rate': 'Medium',
            'mature_height': '60-100 feet',
            'lifespan': '60-80 years',
            'native_region': 'Coastal India',
            "climate_suitability": ["Tropical"],
            "soil_suitability": ["Sandy", "Loamy"],
            'purposes': ['Fruit Production', 'Ornamental', 'Multi-purpose'],
            'environmental_benefits': 'Versatile tree - fruit, oil, fiber, shade. Coastal erosion control',
            'climate_zones': ['Tropical'],
            'soil_types': ['Sandy', 'Loamy'],
            'water_requirement': 'High',
            'drought_tolerance': 'Low',
            'water_needs': 'High',
            'maintenance_level': 'Medium',
            'co2_absorption_kg_year': 32
        },
        {
            'name': 'Tamarind (Imli)',
            'scientific_name': 'Tamarindus indica',
            'growth_rate': 'Slow',
            'mature_height': '60-80 feet',
            'lifespan': '150-200 years',
            'native_region': 'Tropical Africa, naturalized in India',
            "climate_suitability": ["Tropical", "Subtropical"],
            "soil_suitability": ["Loamy", "Sandy", "Clay"],
            'purposes': ['Fruit Production', 'Shade', 'Medicinal'],
            'environmental_benefits': 'Massive shade tree, edible fruit pods, nitrogen-fixing, long-lived',
            'climate_zones': ['Tropical', 'Sub-tropical'],
            'soil_types': ['Loamy', 'Sandy', 'Clay'],
            'water_requirement': 'Low',
            'drought_tolerance': 'High',
            'water_needs': 'Low',
            'maintenance_level': 'Low',
            'co2_absorption_kg_year': 26
        },
        {
            'name': 'Karanj (Pongamia)',
            'scientific_name': 'Pongamia pinnata',
            'growth_rate': 'Fast',
            'mature_height': '50-80 feet',
            'lifespan': '50-100 years',
            'native_region': 'Indian Subcontinent',
            "climate_suitability": ["Tropical", "Subtropical"],
            "soil_suitability": ["Loamy", "Sandy", "Clay", "Rocky"],
            'purposes': ['Biodiversity', 'Biofuel', 'Soil Improvement'],
            'environmental_benefits': 'Nitrogen-fixing, biodiesel production, salt-tolerant, coastal planting',
            'climate_zones': ['Tropical', 'Sub-tropical'],
            'soil_types': ['Loamy', 'Sandy', 'Clay', 'Rocky'],
            'water_requirement': 'Low',
            'drought_tolerance': 'High',
            'water_needs': 'Low',
            'maintenance_level': 'Low',
            'co2_absorption_kg_year': 24
        },
        {
            'name': 'Kadamba',
            'scientific_name': 'Neolamarckia cadamba',
            'growth_rate': 'Very Fast',
            'mature_height': '40-60 feet',
            'lifespan': '70-100 years',
            'native_region': 'South and Southeast Asia',
            "climate_suitability": ["Tropical", "Subtropical"],
            "soil_suitability": ["Loamy", "Clay"],
            'purposes': ['Shade', 'Ornamental', 'Timber', 'Biodiversity'],
            'environmental_benefits': 'Sacred tree, fast-growing, fragrant flowers attract butterflies',
            'climate_zones': ['Tropical', 'Sub-tropical'],
            'soil_types': ['Loamy', 'Clay'],
            'water_requirement': 'High',
            'drought_tolerance': 'Low',
            'water_needs': 'High',
            'maintenance_level': 'Low',
            'co2_absorption_kg_year': 30
        },
        {
            'name': 'Parijat (Night Jasmine)',
            'scientific_name': 'Nyctanthes arbor-tristis',
            'growth_rate': 'Medium',
            'mature_height': '10-15 feet',
            'lifespan': '50-100 years',
            'native_region': 'Indian Subcontinent',
            "climate_suitability": ["Tropical", "Subtropical"],
            "soil_suitability": ["Loamy", "Sandy"],
            'purposes': ['Ornamental', 'Medicinal', 'Fragrance'],
            'environmental_benefits': 'Night-blooming fragrant flowers, medicinal leaves, sacred plant',
            'climate_zones': ['Tropical', 'Sub-tropical'],
            'soil_types': ['Loamy', 'Sandy'],
            'water_requirement': 'Medium',
            'drought_tolerance': 'Medium',
            'water_needs': 'Medium',
            'maintenance_level': 'Low',
            'co2_absorption_kg_year': 15
        },
        {
            'name': 'Bael (Wood Apple)',
            'scientific_name': 'Aegle marmelos',
            'growth_rate': 'Medium',
            'mature_height': '25-35 feet',
            'lifespan': '60-80 years',
            'native_region': 'Indian Subcontinent',
            "climate_suitability": ["Tropical", "Subtropical"],
            "soil_suitability": ["Loamy", "Sandy", "Rocky"],
            'purposes': ['Fruit Production', 'Medicinal'],
            'environmental_benefits': 'Sacred tree, medicinal fruit, drought-resistant, hardy',
            'climate_zones': ['Tropical', 'Sub-tropical'],
            'soil_types': ['Loamy', 'Sandy', 'Rocky'],
            'water_requirement': 'Low',
            'drought_tolerance': 'High',
            'water_needs': 'Low',
            'maintenance_level': 'Low',
            'co2_absorption_kg_year': 19
        },
        {
            'name': 'Custard Apple (Sitaphal)',
            'scientific_name': 'Annona squamosa',
            'growth_rate': 'Fast',
            'mature_height': '15-20 feet',
            'lifespan': '20-30 years',
            'native_region': 'Tropical Americas, widely grown in India',
            "climate_suitability": ["Tropical", "Subtropical"],
            "soil_suitability": ["Loamy", "Sandy"],
            'purposes': ['Fruit Production', 'Ornamental'],
            'environmental_benefits': 'Delicious fruits, low maintenance, attracts pollinators',
            'climate_zones': ['Tropical', 'Sub-tropical'],
            'soil_types': ['Loamy', 'Sandy'],
            'water_requirement': 'Low',
            'drought_tolerance': 'High',
            'water_needs': 'Low',
            'maintenance_level': 'Low',
            'co2_absorption_kg_year': 18
        },
    ]
    
    return trees


def get_tree_details(tree_name):
    """
    Returns detailed information about a specific tree.

    Args:
        tree_name (str): The name of the tree to get details for

    Returns:
        dict: Tree details or None if not found
    """
    trees = get_tree_data()
    for tree in trees:
        if tree["name"].lower() == tree_name.lower():
            return tree
    return None

# tree_data.py — include your existing get_tree_data() list (keep it), and ensure this function exists:
def get_balcony_plants_data():
    """Returns dataset of balcony-friendly plants"""
    balcony_plants = [
        {
            'name': 'Snake Plant (Sansevieria)',
            'scientific_name': 'Dracaena trifasciata',
            'space_required': 'Very Small',
            'sunlight_need': 'Low (2-6 hours)',
            'watering': 'Once every 2-3 weeks',
            'purposes': ['Air Purification', 'Low Maintenance'],
            'care_difficulty': 'Very Easy',
            'growth_rate': 'Slow',
            'max_height': '1-3 feet',
            'benefits': 'Removes toxins, produces oxygen at night',
            'environmental_benefits': 'Air purification, releases oxygen at night',
            'ideal_for': 'Beginners, Low-light spaces',
            'pot_size': '6-8 inches',
            'indoor_ok': True
        },
        {
            'name': 'Tulsi (Holy Basil)',
            'scientific_name': 'Ocimum sanctum',
            'space_required': 'Small',
            'sunlight_need': 'High (6+ hours)',
            'watering': 'Daily (moderate)',
            'purposes': ['Medicinal', 'Edible', 'Air Purification'],
            'care_difficulty': 'Easy',
            'growth_rate': 'Fast',
            'max_height': '1-2 feet',
            'benefits': 'Anti-inflammatory, stress relief, air purifier',
            'environmental_benefits': 'Air purification, releases oxygen at night',
            'ideal_for': 'Sunny balconies',
            'pot_size': '8-10 inches',
            'indoor_ok': True
        },
        {
            'name': 'Money Plant (Pothos)',
            'scientific_name': 'Epipremnum aureum',
            'space_required': 'Very Small',
            'sunlight_need': 'Low to Medium (2-6 hours)',
            'watering': 'Twice a week',
            'purposes': ['Air Purification', 'Aesthetic/Decor', 'Low Maintenance'],
            'care_difficulty': 'Very Easy',
            'growth_rate': 'Fast',
            'max_height': 'Vine (can grow 10+ feet)',
            'benefits': 'Removes formaldehyde, easy propagation',
            'environmental_benefits': 'Air purification, releases oxygen at night',
            'ideal_for': 'Hanging baskets, climbers',
            'pot_size': '6-8 inches',
            'indoor_ok': True
        },
        {
            'name': 'Aloe Vera',
            'scientific_name': 'Aloe barbadensis',
            'space_required': 'Small',
            'sunlight_need': 'High (6+ hours)',
            'watering': 'Once every 2 weeks',
            'purposes': ['Medicinal', 'Low Maintenance'],
            'care_difficulty': 'Easy',
            'growth_rate': 'Slow',
            'max_height': '1-2 feet',
            'benefits': 'Skin healing, air purification',
            'environmental_benefits': 'Air purification, releases oxygen at night',
            'ideal_for': 'Sunny spots, dry climates',
            'pot_size': '8-10 inches',
            'indoor_ok': True
        },
        {
            'name': 'Mint (Pudina)',
            'scientific_name': 'Mentha',
            'space_required': 'Small',
            'sunlight_need': 'Medium (4-6 hours)',
            'watering': 'Daily',
            'purposes': ['Edible', 'Medicinal'],
            'care_difficulty': 'Easy',
            'growth_rate': 'Fast',
            'max_height': '1-1.5 feet',
            'benefits': 'Culinary herb, digestive aid',
            'environmental_benefits': 'Air purification, releases oxygen at night',
            'ideal_for': 'Kitchen gardens',
            'pot_size': '8-10 inches',
            'indoor_ok': True
        },
        {
            'name': 'Spider Plant',
            'scientific_name': 'Chlorophytum comosum',
            'space_required': 'Small',
            'sunlight_need': 'Low to Medium (2-6 hours)',
            'watering': '2-3 times a week',
            'purposes': ['Air Purification', 'Low Maintenance', 'Aesthetic/Decor'],
            'care_difficulty': 'Very Easy',
            'growth_rate': 'Medium',
            'max_height': '1-2 feet',
            'benefits': 'Removes CO and formaldehyde',
            'environmental_benefits': 'Air purification, releases oxygen at night',
            'ideal_for': 'Beginners, hanging baskets',
            'pot_size': '6-8 inches',
            'indoor_ok': True
        },
        {
            'name': 'Coriander (Dhania)',
            'scientific_name': 'Coriandrum sativum',
            'space_required': 'Small',
            'sunlight_need': 'Medium (4-6 hours)',
            'watering': 'Daily (light)',
            'purposes': ['Edible'],
            'care_difficulty': 'Easy',
            'growth_rate': 'Fast',
            'max_height': '1-1.5 feet',
            'benefits': 'Fresh herbs, kitchen garden',
            'environmental_benefits': 'Air purification, releases oxygen at night',
            'ideal_for': 'Balcony herb gardens',
            'pot_size': '8-10 inches',
            'indoor_ok': True
        },
        {
            'name': 'Peace Lily',
            'scientific_name': 'Spathiphyllum',
            'space_required': 'Small to Medium',
            'sunlight_need': 'Low (2-4 hours)',
            'watering': 'Weekly',
            'purposes': ['Air Purification', 'Aesthetic/Decor'],
            'care_difficulty': 'Easy',
            'growth_rate': 'Slow',
            'max_height': '1-2 feet',
            'benefits': 'Removes toxins, beautiful flowers',
            'environmental_benefits': 'Air purification, releases oxygen at night',
            'ideal_for': 'Low-light indoors',
            'pot_size': '8-10 inches',
            'indoor_ok': True
        },
        {
            'name': 'Tomato (Dwarf Variety)',
            'scientific_name': 'Solanum lycopersicum',
            'space_required': 'Medium',
            'sunlight_need': 'High (6-8 hours)',
            'watering': 'Daily',
            'purposes': ['Edible'],
            'care_difficulty': 'Medium',
            'growth_rate': 'Fast',
            'max_height': '2-3 feet',
            'benefits': 'Fresh vegetables',
            'environmental_benefits': 'Air purification, releases oxygen at night',
            'ideal_for': 'Sunny balconies, vegetable gardens',
            'pot_size': '12-14 inches',
            'indoor_ok': True
        },
        {
            'name': 'Areca Palm',
            'scientific_name': 'Dypsis lutescens',
            'space_required': 'Medium to Large',
            'sunlight_need': 'Medium (4-6 hours)',
            'watering': '3 times a week',
            'purposes': ['Air Purification', 'Aesthetic/Decor'],
            'care_difficulty': 'Medium',
            'growth_rate': 'Medium',
            'max_height': '4-6 feet',
            'benefits': 'Humidifies air, removes toxins',
            'environmental_benefits': 'Air purification, releases oxygen at night',
            'ideal_for': 'Large balconies, living rooms',
            'pot_size': '14-16 inches',
            'indoor_ok': True

        },
        # Add these 5 plants to the balcony_plants list in get_balcony_plants_data()
        # Paste them BEFORE the line that says: return balcony_plants

        {
            'name': 'Curry Leaves (Kadi Patta)',
            'scientific_name': 'Murraya koenigii',
            'space_required': 'Medium',
            'sunlight_need': 'High (6-8 hours)',
            'watering': 'Daily',
            'purposes': ['Edible', 'Aromatic', 'Medicinal'],
            'care_difficulty': 'Medium',
            'growth_rate': 'Medium',
            'max_height': '3-4 feet',
            'benefits': 'Fresh leaves for cooking, aids digestion, hair growth',
            'environmental_benefits': 'Natural insect repellent, aromatic air freshener',
            'ideal_for': 'Kitchen gardens, sunny balconies',
            'pot_size': '12-14 inches',
            'indoor_ok': False
        },
        {
            'name': 'Jade Plant',
            'scientific_name': 'Crassula ovata',
            'space_required': 'Very Small',
            'sunlight_need': 'Medium (4-6 hours)',
            'watering': 'Once every 2 weeks',
            'purposes': ['Aesthetic/Decor', 'Low Maintenance'],
            'care_difficulty': 'Very Easy',
            'growth_rate': 'Slow',
            'max_height': '1-2 feet',
            'benefits': 'Good luck symbol, drought-tolerant, beautiful appearance',
            'environmental_benefits': 'Air purification, releases oxygen at night',
            'ideal_for': 'Beginners, low-maintenance gardens',
            'pot_size': '6-8 inches',
            'indoor_ok': True
        },
        {
            'name': 'Rubber Plant',
            'scientific_name': 'Ficus elastica',
            'space_required': 'Medium',
            'sunlight_need': 'Medium (4-6 hours)',
            'watering': 'Twice a week',
            'purposes': ['Air Purification', 'Aesthetic/Decor'],
            'care_difficulty': 'Easy',
            'growth_rate': 'Medium',
            'max_height': '3-5 feet (in pot)',
            'benefits': 'Excellent air purifier, removes formaldehyde',
            'environmental_benefits': 'NASA-approved air purifier, low maintenance',
            'ideal_for': 'Living rooms, large balconies',
            'pot_size': '12-16 inches',
            'indoor_ok': True
        },
        {
            'name': 'Coriander (Dhania)',
            'scientific_name': 'Coriandrum sativum',
            'space_required': 'Small',
            'sunlight_need': 'Medium (4-6 hours)',
            'watering': 'Daily (light)',
            'purposes': ['Edible'],
            'care_difficulty': 'Easy',
            'growth_rate': 'Fast',
            'max_height': '1-1.5 feet',
            'benefits': 'Fresh herbs for cooking, grows quickly',
            'environmental_benefits': 'Attracts beneficial insects',
            'ideal_for': 'Kitchen gardens, beginners',
            'pot_size': '8-10 inches',
            'indoor_ok': False
        },
        {
            'name': 'Boston Fern',
            'scientific_name': 'Nephrolepis exaltata',
            'space_required': 'Medium',
            'sunlight_need': 'Low to Medium (2-4 hours)',
            'watering': '3-4 times a week',
            'purposes': ['Air Purification', 'Aesthetic/Decor'],
            'care_difficulty': 'Medium',
            'growth_rate': 'Medium',
            'max_height': '2-3 feet',
            'benefits': 'Natural humidifier, removes toxins',
            'environmental_benefits': 'Removes formaldehyde and xylene from air',
            'ideal_for': 'Bathrooms, humid spaces, hanging baskets',
            'pot_size': '10-12 inches',
            'indoor_ok': True
        },
        {
            'name': 'Basil (Sweet Basil)',
            'scientific_name': 'Ocimum basilicum',
            'space_required': 'Small',
            'sunlight_need': 'High (6+ hours)',
            'watering': 'Daily',
            'purposes': ['Edible', 'Aromatic', 'Medicinal'],
            'care_difficulty': 'Easy',
            'growth_rate': 'Fast',
            'max_height': '1-2 feet',
            'benefits': 'Culinary herb, pest repellent, anti-inflammatory',
            'environmental_benefits': 'Attracts beneficial insects, natural pest control',
            'ideal_for': 'Kitchen gardens, sunny balconies',
            'pot_size': '8-10 inches',
            'indoor_ok': True
        },
        {
            'name': 'Rosemary',
            'scientific_name': 'Salvia rosmarinus',
            'space_required': 'Small',
            'sunlight_need': 'High (6-8 hours)',
            'watering': 'Once every 2-3 days',
            'purposes': ['Edible', 'Aromatic', 'Medicinal'],
            'care_difficulty': 'Easy',
            'growth_rate': 'Medium',
            'max_height': '2-3 feet',
            'benefits': 'Aromatic herb, culinary use, improves memory',
            'environmental_benefits': 'Drought-tolerant, attracts bees',
            'ideal_for': 'Sunny balconies, herb gardens',
            'pot_size': '10-12 inches',
            'indoor_ok': True
        },
        {
            'name': 'Chili Pepper (Dwarf)',
            'scientific_name': 'Capsicum annuum',
            'space_required': 'Small',
            'sunlight_need': 'High (6-8 hours)',
            'watering': 'Daily',
            'purposes': ['Edible'],
            'care_difficulty': 'Medium',
            'growth_rate': 'Fast',
            'max_height': '1-2 feet',
            'benefits': 'Fresh chillies, compact variety for pots',
            'environmental_benefits': 'Capsaicin production, colorful fruits',
            'ideal_for': 'Sunny balconies, vegetable gardens',
            'pot_size': '10-12 inches',
            'indoor_ok': False
        },
        {
            'name': 'Oregano',
            'scientific_name': 'Origanum vulgare',
            'space_required': 'Small',
            'sunlight_need': 'Medium to High (4-6 hours)',
            'watering': 'Twice a week',
            'purposes': ['Edible', 'Aromatic', 'Medicinal'],
            'care_difficulty': 'Very Easy',
            'growth_rate': 'Medium',
            'max_height': '1-1.5 feet',
            'benefits': 'Pizza herb, antibacterial, drought-tolerant',
            'environmental_benefits': 'Low water needs, pollinator-friendly',
            'ideal_for': 'Kitchen gardens, beginners',
            'pot_size': '8-10 inches',
            'indoor_ok': True
        },
        {
            'name': 'Thyme',
            'scientific_name': 'Thymus vulgaris',
            'space_required': 'Very Small',
            'sunlight_need': 'High (6+ hours)',
            'watering': 'Twice a week',
            'purposes': ['Edible', 'Aromatic', 'Medicinal'],
            'care_difficulty': 'Easy',
            'growth_rate': 'Slow',
            'max_height': '6-12 inches',
            'benefits': 'Culinary herb, antiseptic properties, fragrant',
            'environmental_benefits': 'Extremely drought-tolerant, ground cover',
            'ideal_for': 'Small pots, window boxes',
            'pot_size': '6-8 inches',
            'indoor_ok': True
        },
        {
            'name': 'ZZ Plant',
            'scientific_name': 'Zamioculcas zamiifolia',
            'space_required': 'Small',
            'sunlight_need': 'Low (2-4 hours)',
            'watering': 'Once every 2-3 weeks',
            'purposes': ['Air Purification', 'Low Maintenance', 'Aesthetic/Decor'],
            'care_difficulty': 'Very Easy',
            'growth_rate': 'Slow',
            'max_height': '2-3 feet',
            'benefits': 'Nearly indestructible, tolerates neglect, air purifier',
            'environmental_benefits': 'Removes xylene and toluene from air',
            'ideal_for': 'Low-light spaces, beginners, offices',
            'pot_size': '8-10 inches',
            'indoor_ok': True
        },
        {
            'name': 'Golden Pothos',
            'scientific_name': 'Epipremnum aureum',
            'space_required': 'Very Small',
            'sunlight_need': 'Low to Medium (2-6 hours)',
            'watering': 'Once a week',
            'purposes': ['Air Purification', 'Aesthetic/Decor'],
            'care_difficulty': 'Very Easy',
            'growth_rate': 'Fast',
            'max_height': 'Vine (6-10 feet)',
            'benefits': 'NASA-approved air purifier, golden variegated leaves',
            'environmental_benefits': 'Removes formaldehyde, benzene, xylene',
            'ideal_for': 'Hanging baskets, offices, bathrooms',
            'pot_size': '6-8 inches',
            'indoor_ok': True
        },
        {
            'name': 'Weeping Fig',
            'scientific_name': 'Ficus benjamina',
            'space_required': 'Medium',
            'sunlight_need': 'Medium (4-6 hours)',
            'watering': 'Twice a week',
            'purposes': ['Air Purification', 'Aesthetic/Decor'],
            'care_difficulty': 'Medium',
            'growth_rate': 'Medium',
            'max_height': '3-6 feet (indoor)',
            'benefits': 'Elegant tree-like appearance, air purifier',
            'environmental_benefits': 'Removes formaldehyde, xylene, toluene',
            'ideal_for': 'Living rooms, large balconies',
            'pot_size': '12-16 inches',
            'indoor_ok': True
        },
        {
            'name': 'Croton',
            'scientific_name': 'Codiaeum variegatum',
            'space_required': 'Medium',
            'sunlight_need': 'High (6+ hours)',
            'watering': '3-4 times a week',
            'purposes': ['Aesthetic/Decor'],
            'care_difficulty': 'Medium',
            'growth_rate': 'Medium',
            'max_height': '3-4 feet',
            'benefits': 'Vibrant multicolored leaves, stunning visual appeal',
            'environmental_benefits': 'Air purification, colorful foliage year-round',
            'ideal_for': 'Sunny balconies, decorative displays',
            'pot_size': '10-14 inches',
            'indoor_ok': True
        },
        {
            'name': 'Brahmi (Indian Pennywort)',
            'scientific_name': 'Bacopa monnieri',
            'space_required': 'Small',
            'sunlight_need': 'Medium (4-6 hours)',
            'watering': 'Daily (keep soil moist)',
            'purposes': ['Medicinal', 'Edible'],
            'care_difficulty': 'Easy',
            'growth_rate': 'Medium',
            'max_height': '4-6 inches (ground cover)',
            'benefits': 'Memory enhancement, cognitive function, stress relief, improves concentration',
            'environmental_benefits': 'Ground cover plant, prevents soil erosion',
            'ideal_for': 'Students, elderly, people with anxiety/stress',
            'pot_size': '8-10 inches (wide, shallow)',
            'indoor_ok': True

        },
        {
            'name': 'Ashwagandha (Indian Ginseng)',
            'scientific_name': 'Withania somnifera',
            'space_required': 'Medium',
            'sunlight_need': 'High (6+ hours)',
            'watering': 'Once every 2-3 days',
            'purposes': ['Medicinal'],
            'care_difficulty': 'Medium',
            'growth_rate': 'Medium',
            'max_height': '2-3 feet',
            'benefits': 'Reduces stress/cortisol, boosts immunity, increases strength, improves sleep',
            'environmental_benefits': 'Drought-tolerant, hardy plant',
            'ideal_for': 'Stressed professionals, gym-goers, people with insomnia/anxiety',
            'pot_size': '12-14 inches (deep)',
            'indoor_ok': False

        },
        {
            'name': 'Stevia (Sweet Leaf)',
            'scientific_name': 'Stevia rebaudiana',
            'space_required': 'Small',
            'sunlight_need': 'Medium to High (5-7 hours)',
            'watering': 'Daily (consistent moisture)',
            'purposes': ['Edible', 'Medicinal'],
            'care_difficulty': 'Easy',
            'growth_rate': 'Fast',
            'max_height': '1-2 feet',
            'benefits': 'Natural zero-calorie sweetener, controls blood sugar, safe for diabetics',
            'environmental_benefits': 'Low resource needs, sustainable sugar alternative',
            'ideal_for': 'Diabetics, weight watchers, health-conscious families',
            'pot_size': '10-12 inches',
            'indoor_ok': True

        },
        {
            'name': 'Lemongrass (Hari Chai Patti)',
            'scientific_name': 'Cymbopogon citratus',
            'space_required': 'Medium',
            'sunlight_need': 'High (6+ hours)',
            'watering': 'Daily',
            'purposes': ['Edible', 'Medicinal', 'Aromatic'],
            'care_difficulty': 'Easy',
            'growth_rate': 'Fast',
            'max_height': '2-3 feet',
            'benefits': 'Digestive aid, relieves bloating/gas, immunity booster, natural mosquito repellent',
            'environmental_benefits': 'Natural pest control, citronella oil production',
            'ideal_for': 'People with digestive issues, mosquito-prone areas',
            'pot_size': '12-14 inches',
            'indoor_ok': False

        },
        {
            'name': 'Ajwain (Carom Plant)',
            'scientific_name': 'Trachyspermum ammi',
            'space_required': 'Small',
            'sunlight_need': 'Medium to High (5-7 hours)',
            'watering': 'Once every 2 days',
            'purposes': ['Medicinal', 'Edible'],
            'care_difficulty': 'Medium',
            'growth_rate': 'Medium',
            'max_height': '1-2 feet',
            'benefits': 'Cures indigestion, gas, acidity instantly. Essential Indian home remedy',
            'environmental_benefits': 'Attracts beneficial insects',
            'ideal_for': 'People with chronic acidity, IBS, digestive problems',
            'pot_size': '10-12 inches',
            'indoor_ok': False

        },
        {
            'name': 'Methi (Fenugreek)',
            'scientific_name': 'Trigonella foenum-graecum',
            'space_required': 'Small',
            'sunlight_need': 'Medium (4-6 hours)',
            'watering': 'Daily',
            'purposes': ['Edible', 'Medicinal'],
            'care_difficulty': 'Very Easy',
            'growth_rate': 'Very Fast',
            'max_height': '1-1.5 feet',
            'benefits': 'Controls diabetes, promotes hair growth, increases breast milk production',
            'environmental_benefits': 'Nitrogen-fixing, improves soil',
            'ideal_for': 'Diabetics, new mothers, people with hairfall',
            'pot_size': '8-10 inches',
            'indoor_ok': True

        },
        {
            'name': 'Ginger (Adrak)',
            'scientific_name': 'Zingiber officinale',
            'space_required': 'Medium',
            'sunlight_need': 'Medium (4-6 hours, partial shade ok)',
            'watering': 'Daily (keep moist)',
            'purposes': ['Edible', 'Medicinal'],
            'care_difficulty': 'Easy',
            'growth_rate': 'Slow',
            'max_height': '2-3 feet',
            'benefits': 'Cures cold/cough/sore throat, nausea relief, anti-inflammatory',
            'environmental_benefits': 'Shade-tolerant, tropical plant',
            'ideal_for': 'Everyone - essential kitchen staple',
            'pot_size': '12-14 inches (wide, shallow)',
            'indoor_ok': True

        },
        {
            'name': 'Turmeric (Haldi)',
            'scientific_name': 'Curcuma longa',
            'space_required': 'Medium',
            'sunlight_need': 'Medium (4-6 hours, partial shade ok)',
            'watering': 'Daily (keep moist)',
            'purposes': ['Medicinal', 'Edible'],
            'care_difficulty': 'Easy',
            'growth_rate': 'Slow',
            'max_height': '2-3 feet',
            'benefits': 'Anti-inflammatory, immunity booster, skin healing, joint pain relief',
            'environmental_benefits': 'Shade-tolerant, medicinal rhizome production',
            'ideal_for': 'Everyone - Indian superfood',
            'pot_size': '14-16 inches (deep and wide)',
            'indoor_ok': True

        },
        {
            'name': 'Insulin Plant (Costus)',
            'scientific_name': 'Costus igneus',
            'space_required': 'Medium',
            'sunlight_need': 'Medium (4-6 hours)',
            'watering': 'Daily',
            'purposes': ['Medicinal'],
            'care_difficulty': 'Easy',
            'growth_rate': 'Medium',
            'max_height': '2-3 feet',
            'benefits': 'Controls blood sugar naturally, helps manage diabetes without side effects',
            'environmental_benefits': 'Ornamental foliage, low maintenance',
            'ideal_for': 'Diabetics, pre-diabetics, people with high blood sugar',
            'pot_size': '10-12 inches',
            'indoor_ok': True

        },
        {
            'name': 'Hibiscus (Gudhal)',
            'scientific_name': 'Hibiscus rosa-sinensis',
            'space_required': 'Medium',
            'sunlight_need': 'High (6+ hours)',
            'watering': 'Daily',
            'purposes': ['Medicinal', 'Ornamental'],
            'care_difficulty': 'Easy',
            'growth_rate': 'Fast',
            'max_height': '3-5 feet (in pot)',
            'benefits': 'Stops hairfall, promotes hair growth, controls blood pressure, improves skin',
            'environmental_benefits': 'Beautiful flowers, attracts butterflies and bees',
            'ideal_for': 'People with hairfall, high BP, dull skin',
            'pot_size': '14-16 inches',
            'indoor_ok': False
        },
        {
            'name': 'English Ivy',
            'scientific_name': 'Hedera helix',
            'space_required': 'Small',
            'sunlight_need': 'Low to Medium (2-6 hours)',
            'watering': '2-3 times a week',
            'purposes': ['Air Purification', 'Aesthetic/Decor'],
            'care_difficulty': 'Easy',
            'growth_rate': 'Fast',
            'max_height': 'Vine (6-10 feet)',
            'benefits': 'Excellent air purifier, removes mold spores',
            'environmental_benefits': 'NASA study: reduces airborne fecal matter by 94%',
            'ideal_for': 'Hanging baskets, bathrooms, offices',
            'pot_size': '6-8 inches',
            'indoor_ok': True
        },
    ]
    return balcony_plants